name: 'build'
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
      # This expression means every day at UTC 00:00
      # See https://crontab.guru/examples.html for more examples
      - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: luob/create-my-awesome@c8d292d1422d0146b57bd69237c84d1802c3d353 # v1
      # Commit the change
      # See https://github.com/EndBug/add-and-commit
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          message: 'Update README.md'
        env:
          GITHUB_TOKEN: ${{ github.token }}
